//LOCALHOST
GET http://localhost:8080 HTTP/1.1
###
GET http://localhost:8080/contacts HTTP/1.1 
### 
GET http://localhost:8080/contacts/63be51a0706ae941ca591fe9 HTTP/1.1 
###
GET http://localhost:8080/contacts/63be538d706ae941ca591fea HTTP/1.1 
### 
GET http://localhost:8080/contacts/63be53ed706ae941ca591feb HTTP/1.1
###

###Create contact 
POST http://localhost:8080/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Pedro", 
    "lastName": "Herrera", 
    "email": "ps@test.com", 
    "favoriteColor": "blue", 
    "birthday": "10/20/1990"
}

### Update contact 
PUT http://localhost:8080/contacts/63cc682520162f1b2b9d1247 HTTP/1.1 
Content-type: application/json

{
    "firstName": "Pedro", 
    "lastName": "Herrera", 
    "email": "ps@test.com", 
    "favoriteColor": "Red", 
    "birthday": "10/20/1990"
} 

### Delete contact 
DELETE http://localhost:8080/contacts/63cc682520162f1b2b9d1247 HTTP/1.1

///********************************************
                    //RENDER
///********************************************

###
GET https://arojasescse341.onrender.com HTTP/1.1
###
GET https://arojasescse341.onrender.com/contacts HTTP/1.1
###
GET http://arojasescse341.onrender.com/contacts/63be51a0706ae941ca591fe9 HTTP/1.1
###
GET http://arojasescse341.onrender.com/contacts/63be538d706ae941ca591fea HTTP/1.1
###
GET http://arojasescse341.onrender.com/contacts/63be53ed706ae941ca591feb HTTP/1.1

###Create contact 
POST https://arojasescse341.onrender.com/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Pedro", 
    "lastName": "Herrera", 
    "email": "ps@test.com", 
    "favoriteColor": "blue", 
    "birthday": "10/20/1990"
}

### Update contact 
PUT https://arojasescse341.onrender.com/contacts/63cc6ac6f083472ae8484910 HTTP/1.1 
Content-type: application/json

{
    "firstName": "Pedro", 
    "lastName": "Herrera", 
    "email": "ps@test.com", 
    "favoriteColor": "Red", 
    "birthday": "10/20/1990"
} 

### Delete contact 
DELETE https://arojasescse341.onrender.com/contacts/63cc6ac6f083472ae8484910 HTTP/1.1
